### ISSUE TITLE
Улучшения: добавить возможность лутать определенные предметы, а не весь инвентарь целиком

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#13]
Фильтровать интересующие нас предметы можно по `classid`, который присутствует при запросе к инвентарю steam

GET `https://steamcommunity.com/inventory/xxxxxx/inventory_id/context_id?l=english&count=2000`

response:
```json
{
	"assets": [
		{
			"classid": "12345"
		}
	],
	"descriptions": [
		{
			"market_name": "Some name"
		}
	]
}
```

В дополнении и для удобства пользователя, можно осуществлять фильтрацию с помощью регулярного выражения на имени предмета

В настройках вынести этот пункт в качестве массива, например:
```json
{
"IncludeItemIds": ["123", "12345"],
"IncludeItems": ["frying pan"]
}
```

Помимо прочего можно сделать подобные настройки для игнорирования определенных предметов (Exclude Items), таким образом лутая всё, кроме отмеченных в настройках.

**Comment by Lyrapuff** [comment]
Сделано, спасибо за PR ^^
