### ISSUE TITLE
Баг: загрузка прокси, когда они не указаны

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#19]
Версия: 0.3.0.0

Если в конфиге не указывать прокси, они всё-равно будут загружены (или будет ошибка) из файла proxies.txt, который находится в папке рядом с приложением.

**Comment by Lyrapuff** [comment]
Если не указывать прокси в конфиге, то будет установлено дефолтное значение `proxies.txt`, чтобы не использовать прокси нужно вручную поставить значение `ProxiesFilePath` = ""

Такое поведение осталось со времён, когда луталка делалась под использование вместе с YAR, в данный момент, возможно стоит заменить дефолтное значение на пустую строку.
