### ISSUE TITLE
Баг: Каждый новый поток делает запрос смещения времени

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#24]
![image](https://github.com/SmallTailTeam/BotLooter/assets/47674424/92c03926-3e91-4532-9f13-ea2496e6e695)

В теории не должно быть более 1 запроса за всё время работы приложения.
Если есть возможность передавать данные в потоки, то было бы лучше вынести определение смещения времени в глобальный поток, перед созданием остальных.

**Comment by Lyrapuff** [comment]
Странно, данный запрос делает библиотека SteamAuth и судя по коду, она должна делать его только 1 раз и кешировать на всё время работы приложения.

https://github.com/geel9/SteamAuth/blob/master/SteamAuth/TimeAligner.cs

**Comment by Sadzurami** [comment]
> Странно, данный запрос делает библиотека SteamAuth и судя по коду, она должна делать его только 1 раз и кешировать ответ на всё время работы приложения.
> 
> https://github.com/geel9/SteamAuth/blob/master/SteamAuth/TimeAligner.cs

судя по всему не делает
в теории, может ли помешать запуску потока(или приложения в целом), если один из этих запросов окончится неудачей?

**Comment by Lyrapuff** [comment]
> В теории, может ли помешать запуску потока(или приложения в целом), если один из этих запросов окончится неудачей?

Насколько понимаю, максимум, что может случиться - это бот не сможет авторизоваться (в случае если не установлен RefreshToken), но шанс, что такое случиться очень низок

**Comment by Sadzurami** [comment]
Найден компромис в https://github.com/SmallTailTeam/BotLooter/commit/649f34a9ebc7b561a589513ad6513d171294c748
