### ISSUE TITLE
Улучшения: возможность выбирать LootTradeOfferUrl из списка

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#31]
Текущая реализация сосредоточена на лутании множества ботов на один единственный аккаунт.
В некоторых случаях было бы удобно лутать предметы ни на один аккаунт, а на список аккаунтов.

Например:
```json
"LootTradeOfferUrls": [
  "link1",
  "link2",
  "link3",
]
```

В процессе лутания выбирать аккаунт по принципу round-robin, т.е. лутать на каждый аккаунт последовательно.

Исходя из предложения выше, было бы здорово реализовать ограничитель количества предметов на один аккаунт.

Например, лутать на каждый аккаунт 500 предметов, по достижению лимита - игнорировать этот аккаунт:
```json
"MaxItemsForTradeUrl": 500
```

**Comment by Lyrapuff** [comment]
> Текущая реализация сосредоточена на лутании множества ботов на один единственный аккаунт.
В некоторых случаях было бы удобно лутать предметы ни на один аккаунт, а на список аккаунтов.

Звучит просто и полезно, думаю есть смысл сделать.

> Исходя из предложения выше, было бы здорово реализовать ограничитель количества предметов на один аккаунт.

Если такая ситуация, что на ссылку залутано 495 предметов, а на боте есть 6 предметов, лутать все 6 на ссылку и после её игнорировать, или лутать только 5, а 1 оставлять для следующих аккаунтов?
Так же по достижению лимита количества предметов на всех ссылках, досрочно прекращать лутание?

**Comment by Sadzurami** [comment]
> Если такая ситуация, что на ссылку залутано 495 предметов, а на боте есть 6 предметов, лутать все 6 на ссылку и после её игнорировать, или лутать только 5, а 1 оставлять для следующих аккаунтов?

Сам не уверен как лучше поступать в этой ситуации. Считаю, что пока стоит сделать так, как будет проще в реализации, со временем можно будет переделать при желании.

> Так же по достижению лимита количества предметов на всех ссылках, досрочно прекращать лутание?

Думаю, такое поведение ожидаемо всеми, кто будет пользоваться этой функцией.

**Comment by Sadzurami** [comment]
upd

Считаю, что в описанной выше ситуации нужно будет лутать 5, а с оставшимися предметами решать делать что-то иное.

Т.к. ситуация может быть следующая: в конфиге будет указан максимум предметов для лута 10, а подходящих предметов у бота будет 50.
