### ISSUE TITLE
Улучшения: подсчет кол-ва отправленных предеметов.

### ISSUE THREAD

**Issue by Plimm** [SmallTailTeam/BotLooter#33]
Добавить подсчет отправленных предметов после завершения работы. 
Также если это возможно, добавить параметр который перестанет лутать предметы на аккаунт, если указать определенную ценность инвентаря при которой: Бот либо останавливается, либо продолжает лутать на следующий по списку аккаунт.

```
"MaxValueOfInventory": 500 "Сумма в долларах, если возможно то в других валютах"
```

**Comment by Sadzurami** [comment]
> Добавить подсчет отправленных предметов после завершения работы.
Это реально и должно быть не сложно реализовать.

> Также если это возможно, добавить параметр который перестанет лутать предметы на аккаунт, если указать определенную ценность инвентаря при которой: Бот либо останавливается, либо продолжает лутать на следующий по списку аккаунт.

Вот это уже сложнее, необходимо будет вместо предоставления ссылки для лутания - предоставлять учетные данные аккаунтов, на которые необходимо лутать. Помимо прочего, для реализации этой задачи нужно будет добавить много логики для парсинга цен предметов и подсчёта стоимости. 

Сделать это реально, но очень сомневаюсь, что подобный функционал входит в рамки задач, которые ожидаются от приложения для лутания. Для реализации этой задачи лучше делать отдельное приложение или форк.

Конечно моё мнение может отличаться от мнения @Lyrapuff, подождём ответа.

**Comment by Lyrapuff** [comment]
Вывод статистики после завершения работы - скорее всего будет реализовано, а рассчитывать стоимость инвентаря - согласна с сообщением выше

**Comment by Sadzurami** [comment]
Сделано в https://github.com/SmallTailTeam/BotLooter/commit/d41bb7fcf4bb8ba6b5b4cd66a90eda1a6cc4aa3e
