### ISSUE TITLE
Улучшения: передавть предметы определеенного типа

### ISSUE THREAD

**Issue by Plimm** [SmallTailTeam/BotLooter#34]
Добавить преедачу предметов определенного типа в зависимости от игры. Например в ксго: Граффити, винтовки, инструменты и т.д.
Также вместо типа, можно сделать качество предмета, например: Базовый, ширптореб, армейское, тайное и т.д.

**Comment by alexmaidan** [comment]
Можно просто слутать кейсы используя список латаемых предметов, а потом
просто весь инвентарь слутать

**Comment by Sadzurami** [comment]
Тема слишком специфичная и не универсальная для каждого инвентаря.
Проще будет найти список нужных предметов и внести их названия в конфиг.
