### ISSUE TITLE
Улучшения: не лутать ботов повторно

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#35]
Пожалуй одна из самых важных вещей в процессе лутания до сих пор не реализована.
Пока что у нас нет механизма для игнорирования аккаунтов, которые ранее были залутаны.

Полезно это будет всем, т.к. трейды стима не идеальны, часто бывают ошибки из-за которых мы вынуждены лутать повторно.

Для реализации этой задачи предлагаю универсальную идею:

Использовать `файл игнорирования`.

```json
"IgnoreAccountsFilePath": "ignore-list.txt"
```

В этом файле будут находится юзернеймы, которые необходимо игнорировать в процессе импорта ботов.
В процессе лутания мы должны будем периодически сбрасывать в этот файл юзернеймы ботов, которые закончили своё лутание успешно.

**Comment by Sadzurami** [comment]
Возможно, именно фильтрации ботов - не совсем задача луталки, но экспорт юзернеймов вполне.
Можно реализовать хотя бы именно экспорт юзернеймов и фильтровать аккаунты самостоятельно впоследствии.

Идею с фильтрацией написал для удобства пользователя.

**Comment by Lyrapuff** [comment]
Думаю, что имеет смысл реализовать сразу и, экспорт логинов с успешным лутанием, и файл игнорирования

**Comment by Lyrapuff** [comment]
Добавлено в 402c5c64cf81f43684f9149e0d9ec11a52fd9aab и 30e35cded4f1ce0c7f680520b552ed26fd9ab2e4
На момент написания, не протестировано.

**Comment by Sadzurami** [comment]
> Добавлено в [402c5c6](https://github.com/SmallTailTeam/BotLooter/commit/402c5c64cf81f43684f9149e0d9ec11a52fd9aab) и [30e35cd](https://github.com/SmallTailTeam/BotLooter/commit/30e35cded4f1ce0c7f680520b552ed26fd9ab2e4) На момент написания, не протестировано.

протестирую, спасибо большое
