### ISSUE TITLE
Лутание по качеству предмета

### ISSUE THREAD

**Issue by Plimm** [SmallTailTeam/BotLooter#51]
Предлагаю сделать лутание предметов по качетсву, так как для тех кто фармит в кске, не охота лутать ширп вместе с кесами на один акк. Лучше будет лутать кейсы и скины выше армейского

**Comment by Lyrapuff** [comment]
Возможность реализовать такое поведение появилась в релизе [0.3.6.0](https://github.com/SmallTailTeam/BotLooter/releases/tag/0.3.6.0), добавлено с #53
