### ISSUE TITLE
[Bug] Unhandled exception

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#58]
Версия pre-release 0.3.7.0

![image](https://github.com/SmallTailTeam/BotLooter/assets/47674424/982577c9-cfc7-4c32-b0d3-f508926d066a)

**Comment by Lyrapuff** [comment]
Похоже, что регулярка в `TradeOfferUrlRegex` не смогла корректно спарсить ссылку на обмен и достать оттуда поле partner

**Comment by Sadzurami** [comment]
возможно сделал фикс в #59
